env:
  global:
  - secure: lAbzQCaQ2u5y4LjNAQNxkx9KKKM5X8TmKILuVQBrgPOZhT2wxtRWjb7UtSrD5KAopEiX/Vuna+oxwj6qRSS4UErg5bpq9OY4+XAaugt/qUkCr37wuvFNwnRz5h4kkk48jpI1UNcRNUMcIHO8N/LQrn9YiBp6Ytdhr9PxQ8bGp79uhPSx2aLEf7ADwJNcYu4tN1xGsNrH/KHeZ4dJ8R694QW9ozo9nsHbrM0ILPJFynS1mHkpaF/up6+bZ0hqMAdvIyds5cSZigIT5iuMKIzIAAwiijphaGNvb3WJH5tEsCr5i/pojuRsXuPA5difMW3Q+bk8GB6Z/8i6v+rhgvtrhSvd0ZGzUC0QcBlajWb0ib1mqXERA58udqcxRmWINRAOtj6X7F9UWr8tyU9PLBWWAxA7Ul2+MsBLZB4YyxeX+jC/IbF1fo8bKnmf7OFsAHoo9fovKbbqvq+3KBeImj1JQbt0XL3HzBuUnSbuapWKM6X89lqZEOlg8dU+bcnhNIMD+DPA1yHxLgEi79j1j/WASm34g+zkQTmo+4YklIfq0mIVy4id+EfYOfHABFusfxlNOodHKnSfSgv+8FkftPlTdC2iDe2FLGwK1vMFn2adA4EJ8ZTmkY9BFO68RxSceU0rnZUdbq55dfatE4GNg0Sqq+th4H4b7O9o41sao8XoBuc=
  - FFIDest=$TRAVIS_BUILD_DIR/app/api/ffi
  - PROJECT_NAME=safe_launcher

matrix:
  include:
  - os: linux
    env: |
      PLATFORM=linux-x64
      PLATFORM_NAME=linux
  - os: osx
    env: |
      PLATFORM=osx-x64
      PLATFORM_NAME=darwin
language: generic

python:
  - '2.7'

osx_image: xcode7.2

sudo: required

dist: trusty

cache:
  cargo: true

addons:
  apt:
    packages:
      - xvfb

before_install:
  - export PROJECT_VERSION=$(git log -1 | grep -i "version change to" | sed "s/.*[vV]ersion change to v\{0,1\}//")
  - export PROJECT_NAME=$(grep -i 'productName' $TRAVIS_BUILD_DIR/app/package.json | sed 's/.*"productName":."//' | sed 's/\(",\)$//')
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PROJECT_NAME=$(tr '[:upper:]' '[:lower:]' <<< $PROJECT_NAME | tr " " _); fi
  - export PACKAGE_NAME="$PROJECT_NAME-v$PROJECT_VERSION-$PLATFORM_NAME-x64"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libnotify4; sudo apt-get install libgconf-2-4; fi
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - curl -sSf https://static.rust-lang.org/rustup.sh | sh
  - rustc -V
  - cargo -V
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh
  - ". install_libsodium.sh"
  - nvm --version
  - nvm install 5.5.0
  - node --version
  - npm --version
  - python --version

script:
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/maidsafe/safe_core.git && cd safe_core
  - cargo build --release --verbose --features use-mock-routing
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp ./target/release/libsafe_core.dylib $FFIDest; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp ./target/release/libsafe_core.so $FFIDest; fi
  - cd $TRAVIS_BUILD_DIR
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm install -g electron-prebuilt; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm install -g gulp-electron-mocha; fi
  - npm test

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - cd safe_core
  - cargo build --release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp ./target/release/libsafe_core.so $FFIDest; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp ./target/release/libsafe_core.dylib $FFIDest; fi
  - cd $TRAVIS_BUILD_DIR
  - git config --global user.name shankar2105
  - git config --global user.email shankar21mail@gmail.com
  - git fetch --tags
  - if [ -z $(git tag -l "$PROJECT_VERSION") ]; then git tag $PROJECT_VERSION -am "Version $PROJECT_VERSION" $TRAVIS_COMMIT; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} tag $PROJECT_VERSION > /dev/null 2>&1; fi
  - npm run package
  - git clone https://${GH_TOKEN}@github.com/maidsafe/release_config
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv release_config/safe_launcher/safe_launcher.crust.config app_dist/$PACKAGE_NAME/$PACKAGE_NAME.crust.config; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv release_config/safe_launcher/* app_dist/$PACKAGE_NAME/; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv release_config/safe_launcher/safe_launcher.crust.config release_config/$PACKAGE_NAME/$PACKAGE_NAME\ Helper.crust.config; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv release_config/safe_launcher/* app_dist/$PACKAGE_NAME/$PACKAGE_NAME.app/Contents/Frameworks/$PACKAGE_NAME\ Helper.app/Contents/MacOS/; fi
  - pushd ./app_dist
  - tar czf ../${PROJECT_NAME}-v${PROJECT_VERSION}-${PLATFORM}.tar.gz *
  - popd
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "${PROJECT_NAME}-v${PROJECT_VERSION}-${PLATFORM}.tar.gz"
  skip_cleanup: true
  tag_name: "${PROJECT_VERSION}"
  draft: true
  on:
    all_branches: true
    condition: |
      (-n "$PROJECT_VERSION") && (-n "$PLATFORM")
