platform:
  - x64

image: Previous Visual Studio 2015

os: unstable

environment:
  nodejs_version: "6.4.0"
  global:
    Features: "use-mock-routing"
    RUST_BACKTRACE: 1

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        cmd /c curl -fsSL -o "Install Rustup.ps1" "$url/Install%20Rustup.ps1"
        cmd /c curl -fsSL -o "Build.ps1" "$url/Build.ps1"
        cmd /c curl -fsSL -o "Run Tests.ps1" "$url/Run%20Tests.ps1"
        . ".\Install Rustup.ps1"
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set npm_config_arch=%PLATFORM:x86=ia32%
  - node --version
  - npm --version
  - choco install googlechrome
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/maidsafe/safe_core.git && cd safe_core
  - git tag -l
  - git checkout tags/0.20.0
  - cargo build --release --verbose --features use-mock-routing
  - copy target\release\safe_core.dll %APPVEYOR_BUILD_FOLDER%\app\ffi
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  - npm config set msvs_version=2015
  - npm install node-gyp
  - npm install --progress false --depth 0
  - npm run rebuild-native
  - npm run lint
  - npm run build-test
  - npm test
