platform:
  - x64
image: Visual Studio 2013
os: unstable
environment:
  nodejs_version: "5.5.0"
  global:
    Features: "use-mock-routing"
    RUST_BACKTRACE: 1
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
        Start-FileDownload "$url/Install%20Rustup.ps1" -FileName "Install Rustup.ps1"
        Start-FileDownload "$url/Build.ps1" -FileName "Build.ps1"
        Start-FileDownload "$url/Run%20Tests.ps1" -FileName "Run Tests.ps1"
        . ".\Install Rustup.ps1"

  - node --version
  - npm --version
  - set npm_config_arch=%PLATFORM:x86=ia32%
  - npm install -g json
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/maidsafe/safe_core.git && cd safe_core
  - cargo build --release --verbose --features use-mock-routing
  - copy target\release\safe_core.dll %APPVEYOR_BUILD_FOLDER%\app\api\ffi
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  - npm config set msvs_version=2013
  - npm install --progress false --depth 0
  - npm test
