const ActionTypes = {
  TOAST_NETWORK_STATUS: 'TOAST_NETWORK_STATUS',
  RETRYING_NETWORK: 'RETRYING_NETWORK',
  SET_NETWORK_DISCONNECTED: 'SET_NETWORK_DISCONNECTED',
  SET_NETWORK_CONNECTED: 'SET_NETWORK_CONNECTED',
  SET_NETWORK_CONNECTING: 'SET_NETWORK_CONNECTING',
  TOGGLE_PROXY: 'TOGGLE_PROXY',
  FINISH_INITIAL_PROXY_SETTINGS: 'FINISH_INITIAL_PROXY_SETTINGS',
  AUTH_PROCESSING: 'AUTH_PROCESSING',
  AUTH_CANCEL: 'AUTH_CANCEL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_STATE_NEXT: 'REGISTER_STATE_NEXT',
  REGISTER_STATE_BACK: 'REGISTER_STATE_BACK',
  SET_REGISTER_STATE: 'SET_REGISTER_STATE',
  RESET_USER: 'RESET_USER',
};

export default ActionTypes;
