const ActionTypes = {
  TOAST_NETWORK_STATUS: 'TOAST_NETWORK_STATUS',
  RETRYING_NETWORK: 'RETRYING_NETWORK',
  SET_NETWORK_DISCONNECTED: 'SET_NETWORK_DISCONNECTED',
  SET_NETWORK_CONNECTED: 'SET_NETWORK_CONNECTED',
  SET_NETWORK_CONNECTING: 'SET_NETWORK_CONNECTING',
  TOGGLE_PROXY: 'TOGGLE_PROXY',
  FINISH_INITIAL_PROXY_SETTINGS: 'FINISH_INITIAL_PROXY_SETTINGS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
};

export default ActionTypes;
